/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libproyecto_grafos */

#ifndef _Included_libproyecto_grafos
#define _Included_libproyecto_grafos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libproyecto_grafos
 * Method:    funcionAsignacion
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libproyecto_grafos_funcionAsignacion
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
